#!/usr/bin/env bash

# \brief Displays the help and exits the program
function gentooinstall_help
{
	echo "$DISPLAYNAME $VERSION"
	echo "This script automates most of the steps in the Gentoo Handbook."
	echo "Usage:"
	echo "  gentooinstall [options]"
	echo "Options:"
	echo "  -a, --architecture amd64"
	echo "    Which architecture to install."
	echo "  -b, --block-device /tmp/none"
	echo "    Which block device to partition."
	echo "  --block-device-partition-alignment 4194304"
	echo "    What size to align the partitions along."
	echo "  --block-device-partition-type gpt"
	echo "    What type of a partition table to create: gpt or msdos."
	echo "  --chroot false"
	echo "    Chroot into the destination directory for the current phase."
	echo "  -d, --destination /mnt/gentoo"
	echo "    Where to install."
	echo "  -h, --help"
	echo "    Display this help message and exit."
	echo "  -p, --phase phase1,phase2,..."
	echo "    A comma-separated list of which phases to run:"
	echo "      partition"
	echo "      mount"
	echo "      stage3"
	echo "      stage3digest"
	echo "      stage3hash"
	echo "      extract"
	echo "      qemu"
	echo "      deletestage3"
	echo "      resolvconf"
	echo "      makeconf"
	echo "      mountchroot"
	echo "      portage"
	echo "      timezone"
	echo "      locale"
	echo "      update"
	echo "  --portage latest"
	echo "    Which portage snapshot to install, latest or a URL to a specific file to download."
	echo "  --stage3 latest"
	echo "    Which stage3 tarball to install, latest or a URL to a specific file to download."
	echo "  -t, --timezone \"UTC\""
	echo "    Which timezone to configure."
	echo "Examples:"
	echo "  gentooinstall -a amd64 -d /mnt/gentoo -t \"Canada/Mountain\""
	echo "  gentooinstall -a amd64 -d /mnt/gentoo --portage \"https://www.example.com/portage-20160320.tar.bz2\""
	exit
}

# \brief The main function of this script
function gentooinstall_main
{
	#iterate through each phase
	local CURRENT_PHASE=$(echo -n "$PHASES" | sed -r -e 's/([^,]+),?.*?/\1/')
	local REMAINING_PHASES=$(echo -n "$PHASES" | sed -r -e 's/[^,]+,?(.*?)/\1/')
	while [ "$CURRENT_PHASE" != "" ]; do
		case "$CURRENT_PHASE" in
			"partition")    gentooinstall_phase_partition;;
			"mount")        gentooinstall_phase_mount;;
			"stage3")       gentooinstall_phase_stage3;;
			"stage3digest") gentooinstall_phase_stage3digest;;
			"stage3hash")   gentooinstall_phase_stage3hash;;
			"extract")      gentooinstall_phase_extract;;
			"qemu")         gentooinstall_phase_qemu;;
			"deletestage3") gentooinstall_phase_deletestage3;;
			"resolvconf")   gentooinstall_phase_resolvconf;;
			"makeconf")     gentooinstall_phase_makeconf;;
			"mountchroot")  gentooinstall_phase_mountchroot;;
			"portage")      gentooinstall_phase_portage;;
			"timezone")     gentooinstall_phase_timezone;;
			"locale")       gentooinstall_phase_locale;;
			"update")       gentooinstall_phase_update;;
			"vim")          gentooinstall_phase_vim;;
			"syslogng")     gentooinstall_phase_syslogng;;
			"packages")     gentooinstall_phase_packages;;
			"xorg")         gentooinstall_phase_xorg;;
			"kde")          gentooinstall_phase_kde;;
			*)
				echo "error: unknown phase: \"$CURRENT_PHASE\""
				break
				;;
		esac
		CURRENT_PHASE=$(echo -n "$REMAINING_PHASES" | sed -r -e 's/([^,]+),?.*?/\1/')
		REMAINING_PHASES=$(echo -n "$REMAINING_PHASES" | sed -r -e 's/[^,]+,?(.*?)/\1/')
	done
}

function gentooinstall_phase_deletestage3
{
	rm "$DESTINATION"/stage3-*.tar.bz2*
}

function gentooinstall_phase_extract
{
	local STAGE3=$(ls "$DESTINATION"/stage3-*.tar.bz2)
	echo -n "Extracting \"$STAGE3\" to \"$DESTINATION\"... "
	tar xjpf "$DESTINATION"/stage3-*.tar.bz2 -C "$DESTINATION" --xattrs
	echo "Done."
}

function gentooinstall_phase_kde
{
	if $CHROOT; then
		env-update
		source /etc/profile
		
		case "$ARCHITECTURE" in
			"amd64")
				eselect profile set "default/linux/amd64/13.0/desktop/kde"
				;;
			"armv4tl")
				eselect profile set "default/linux/arm/13.0/armv4/desktop/kde"
				;;
			"armv5tel")
				eselect profile set "default/linux/arm/13.0/armv5te/desktop/kde"
				;;
			"armv6j")
				eselect profile set "default/linux/arm/13.0/armv6j/desktop/kde"
				;;
			"armv6j_hardfp")
				eselect profile set "default/linux/arm/13.0/armv6j/desktop/kde"
				;;
			"armv7a")
				eselect profile set "default/linux/arm/13.0/armv7a/desktop/kde"
				;;
			"armv7a_hardfp")
				eselect profile set "default/linux/arm/13.0/armv7a/desktop/kde"
				;;
			*) exit 1;;
		esac
		env-update
		source /etc/profile
		emerge -uDN --with-bdeps=y --quiet world
		
		emerge --backtrack=65536 --quiet kde-apps/kdebase-meta
		
		# update /etc/conf.d/xdm so the display manager is kdm instead of xdm
		echo "LS0tIC9ldGMvY29uZi5kL3hkbS5vbGQJMjAxNi0wNy0yOCAxNTo0ODozOC4wMzAxMDIwMTcgKzAwMDAKKysrIC9ldGMvY29uZi5kL3hkbQkyMDE2LTA3LTI4IDE1OjQ4OjQzLjE0NzAzMzIyMSArMDAwMApAQCAtNyw0ICs3LDQgQEAKIAogIyBXaGF0IGRpc3BsYXkgbWFuYWdlciBkbyB5b3UgdXNlID8gIFsgeGRtIHwgZ2RtIHwga2RtIHwgZ3BlIHwgZW50cmFuY2UgXQogIyBOT1RFOiBJZiB0aGlzIGlzIHNldCBpbiAvZXRjL3JjLmNvbmYsIHRoYXQgc2V0dGluZyB3aWxsIG92ZXJyaWRlIHRoaXMgb25lLgotRElTUExBWU1BTkFHRVI9InhkbSIKK0RJU1BMQVlNQU5BR0VSPSJrZG0iCg==" \
			| base64 --decode | patch -p0
		
		rc-update add dbus default
		rc-update add xdm default
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall.sh --chroot --phase kde
	fi
}

function gentooinstall_phase_locale
{
	if $CHROOT; then
		env-update
		source /etc/profile
		echo "en_US ISO-8859-1" >>/etc/locale.gen
		echo "en_US.UTF-8 UTF-8" >>/etc/locale.gen
		locale-gen
		eselect locale set en_US.utf8
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase locale
	fi
}

function gentooinstall_phase_makeconf
{
	echo "Patching /etc/portage/make.conf"
	echo "CiMgaGFyZHdhcmUKI0NQVV9GTEFHU19YODY9IiRVU0UgM2Rub3cgM2Rub3dleHQgYXZ4IG1teCBtbXhleHQgc3NlIHNzZTIgc3NzZTMiCiNVU0U9IiRVU0UgYWNwaSBhcG0gYmx1ZXRvb3RoIGNwdWRldGVjdGlvbiBoZGR0ZW1wIGllZWUxMzk0IGxtX3NlbnNvcnMgc21wIHVzYiB3aWZpIgojIHNlcnZlcgojVVNFPSIkVVNFIGFjbCBjcnlwdCBjdXBzIGljdSBpZG4gaW1hcCBpcHY2IGt2bSBsYXJnZWZpbGUgbGRhcCBsem1hIGx6byBtbWFwIG11bHRpbGliIG5ldHdvcmsgcG9zaXggc2FtYmEgc2hhcmVkbWVtIHNvY2tldHMgc3NsIHN5c2xvZyB0aHJlYWRzIHVkZXYgdW5pY29kZSB2bmMgeGF0dHIiCiMgZGVza3RvcAojVVNFPSIkVVNFIHB1bHNlYXVkaW8iCgojQUNDRVBUX0xJQ0VOU0U9IioiCiNJTlBVVF9ERVZJQ0VTPSJldmRldiBrZXlib2FyZCBtb3VzZSBzeW5hcHRpY3MiCiNMSU5HVUFTPSJlbiBlbl9VUyIK" \
		| base64 --decode >>"$DESTINATION"/etc/portage/make.conf
}

function gentooinstall_phase_mount
{
	mkdir -p "$DESTINATION"
	mount "$DEVICE"*2 "$DESTINATION"
	mkdir -p "$DESTINATION"/boot
	mount "$DEVICE"*1 "$DESTINATION"/boot
}

function gentooinstall_phase_mountchroot
{
	mount -t proc none "$DESTINATION/proc"
	mount --rbind /sys "$DESTINATION/sys"
	mount --make-rslave "$DESTINATION/sys"
	mount --rbind /dev "$DESTINATION/dev"
	mount --make-rslave "$DESTINATION/dev"
}

function gentooinstall_phase_packages
{
	if $CHROOT; then
		env-update
		source /etc/profile
		
		CONFIG_PROTECT_MASK="$CONFIG_PROTECT_MASK /etc/portage/package.use/zzzz-autounmask-write /etc/portage/package.accept_keywords"

		emerge --quiet --autounmask-write net-misc/ntp || emerge --resume
		if [ $? -eq 0 ]; then
			rc-update add ntpd default
		fi
		
		emerge --quiet --autounmask-write sys-power/acpid || emerge --resume
		if [ $? -eq 0 ]; then
			rc-update add acpid default
		fi
		
		emerge --quiet --autounmask-write sys-process/vixie-cron || emerge --resume
		if [ $? -eq 0 ]; then
			rc-update add vixie-cron default
		fi
		
		emerge --quiet --autounmask-write app-admin/sudo || emerge --resume
		if [ $? -eq 0 ]; then
			# update /etc/sudoers to allow members of the wheel group to run any command via sudo
			echo "LS0tIC9ldGMvc3Vkb2VycwkyMDE2LTA0LTI4IDE5OjU5OjU3LjYzMzE5NTE5NSAtMDYwMAorKysgL2V0Yy9zdWRvZXJzLnBhdGNoZWQJMjAxNi0wNC0yOSAxMzo1NDoyNy4yNzk5NjMzMjQgLTA2MDAKQEAgLTc5LDcgKzc5LDcgQEAKIHJvb3QgQUxMPShBTEwpIEFMTAogCiAjIyBVbmNvbW1lbnQgdG8gYWxsb3cgbWVtYmVycyBvZiBncm91cCB3aGVlbCB0byBleGVjdXRlIGFueSBjb21tYW5kCi0jICV3aGVlbCBBTEw9KEFMTCkgQUxMCisld2hlZWwgQUxMPShBTEwpIEFMTAogCiAjIyBTYW1lIHRoaW5nIHdpdGhvdXQgYSBwYXNzd29yZAogIyAld2hlZWwgQUxMPShBTEwpIE5PUEFTU1dEOiBBTEwK" \
				| base64 --decode | patch -p0
		fi
		
		emerge --quiet app-portage/gentoolkit
		
		emerge --quiet --autounmask-write \
			app-editors/nano \
			app-misc/screen \
			net-analyzer/arping \
			net-analyzer/bmon \
			net-analyzer/tcpdump \
			net-analyzer/traceroute \
			net-dns/bind-tools \
			net-dns/openresolv \
			net-firewall/iptables \
			net-fs/nfs-utils \
			net-misc/bridge-utils \
			net-misc/dhcpcd \
			net-misc/whois \
			sys-apps/hdparm \
			sys-apps/iproute2 \
			sys-apps/lm_sensors \
			sys-apps/netplug \
			sys-apps/pciutils \
			sys-apps/smartmontools \
			sys-apps/usb_modeswitch \
			sys-apps/usbutils \
			sys-block/parted \
			sys-fs/btrfs-progs \
			sys-fs/ddrescue \
			sys-fs/dosfstools \
			sys-fs/exfat-utils \
			sys-fs/fuse-exfat \
			sys-fs/lvm2 \
			sys-fs/mdadm \
			sys-kernel/linux-firmware \
			sys-process/atop \
			sys-process/iotop \
			sys-process/lsof \
			|| emerge --resume
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase packages
	fi
}

function gentooinstall_phase_partition
{
	if [ ! -b "$DEVICE" ]; then
		echo "error: \"$DEVICE\" is not a block device"
		return 1
	fi
	if mount | grep "$DEVICE"; then
		echo "error: \"$DEVICE\" is currently mounted"
		return 2
	fi
	
	local DEVICE_MODEL=$(hdparm -I "$DEVICE" 2>/dev/null | grep --text 'Model Number' | cut -d ':' -f 2 | sed -r -e 's/ *(.*?) */\1/')
	local DEVICE_SERIAL=$(hdparm -I "$DEVICE" 2>/dev/null | grep --text 'Serial Number' | cut -d ':' -f 2 | sed -r -e 's/ *(.*?) */\1/')
	local DEVICE_SIZE=$(blockdev --getsize64 "$DEVICE")
	
	local BLOCK_SIZE=$DEVICE_PARTITION_ALIGNMENT
	local DEVICE_BLOCKS=$(($DEVICE_SIZE/$BLOCK_SIZE))
	local BOOT_BLOCKS=$((128*1024*1024/$BLOCK_SIZE))
	if [ $(($BOOT_BLOCKS*$BLOCK_SIZE)) -lt $((128*1024*1024)) ]; then
		BOOT_BLOCKS=$((128*1024*1024/$BLOCK_SIZE + 1))
	fi
	local SWAP_BLOCKS=$((4096*1024*1024/$BLOCK_SIZE))
	if [ $(($SWAP_BLOCKS*$BLOCK_SIZE)) -lt $((4096*1024*1024)) ]; then
		SWAP_BLOCKS=$((4096*1024*1024/$BLOCK_SIZE + 1))
	fi
	local ROOT_BLOCKS=$(($DEVICE_BLOCKS-1-$BOOT_BLOCKS-$SWAP_BLOCKS ))
	
	echo "Formatting with a $DEVICE_PARTITION_TYPE partition table and filesystems:"
	echo "  Device: $DEVICE"
	if [ "$DEVICE_MODEL" != "" ]; then
		echo "  Model Number: $DEVICE_MODEL"
	fi
	if [ "$DEVICE_SERIAL" != "" ]; then
		echo "  Serial Number: $DEVICE_SERIAL"
	fi
	echo "  Size: $DEVICE_SIZE Bytes"
	echo "  Partition Alignment Block Size: $BLOCK_SIZE Bytes"
	echo "  Boot Partition Size: $BOOT_BLOCKS Blocks"
	echo "  Root Partition Size: $ROOT_BLOCKS Blocks"
	echo "  Swap Partition Size: $SWAP_BLOCKS Blocks"
	echo "Press CTRL+C to cancel"
	for SECONDS in `seq 10 -1 1`; do
		printf "\r${SECONDS} ... "
		sleep 1
	done
	printf "\r0 ... \n"
	
	echo -n "Creating the partition table..."
	parted --script "$DEVICE" mklabel $DEVICE_PARTITION_TYPE
	echo " done."
	echo -n "Creating the boot partition..."
	parted --script "$DEVICE" mkpart primary fat32 "$BLOCK_SIZE"b $(($BLOCK_SIZE + $BLOCK_SIZE*$BOOT_BLOCKS - 1))b
	parted --script "$DEVICE" set 1 boot on
	mkfs.vfat -F 32 "$DEVICE"*1 >/dev/null 2>/dev/null
	echo " done."
	echo -n "Creating the root partition..."
	parted --script "$DEVICE" mkpart primary ext4 $(($BLOCK_SIZE + $BLOCK_SIZE*$BOOT_BLOCKS))b $(($BLOCK_SIZE + $BLOCK_SIZE*$BOOT_BLOCKS + $BLOCK_SIZE*$ROOT_BLOCKS - 1))b
	mkfs.ext4 -b 4096 -F "$DEVICE"*2 >/dev/null 2>/dev/null
	echo " done."
	echo -n "Creating the swap partition..."
	parted --script "$DEVICE" mkpart primary ext4 $(($BLOCK_SIZE + $BLOCK_SIZE*$BOOT_BLOCKS + $BLOCK_SIZE*$ROOT_BLOCKS))b $(($BLOCK_SIZE + $BLOCK_SIZE*$BOOT_BLOCKS + $BLOCK_SIZE*$ROOT_BLOCKS + $BLOCK_SIZE*$SWAP_BLOCKS - 1))b
	mkswap "$DEVICE"*3 >/dev/null 2>/dev/null
	echo " done."
	echo -n "Activating the swap partition..."
	swapon "$DEVICE"*3
	echo " done."
}

function gentooinstall_phase_portage
{
	if $CHROOT; then
		env-update
		source /etc/profile
		if [ "$PORTAGE" = "latest" ]; then
			emerge-webrsync --quiet >/dev/null 2>/dev/null
			emerge --sync --quiet
		else
			wget "$PORTAGE" -O /tmp/portage.tar.bz2
			tar xjpf /tmp/portage.tar.bz2 -C /usr
		fi
		mkdir /etc/portage/package.use
		touch /etc/portage/package.use/zzzz-autounmask-write
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase portage --portage "$PORTAGE"
	fi
}

# Copies static qemu binaries into the install destionation
function gentooinstall_phase_qemu
{
	case "$ARCHITECTURE" in
		"armv4tl" | "armv5tel" | "armv6j" | "armv6j_hardfp" | "armv7a" | "armv7a_hardfp")
			if [ ! -d /proc/sys/fs/binfmt_misc ]; then
				echo "error: kernel support for 'misc binaries' is required"
				return 1
			elif ! file /usr/bin/qemu-arm | grep 'statically linked' >/dev/null; then
				echo "error: the file \"/usr/bin/qemu-arm\" is not a static binary"
				return 2
			elif ! "$DESTINATION"/bin/busybox true; then
				echo "error: dynamic translation test failed for \"$DESTINATION//bin/busybox test\""
				return 2
			fi
			cp /usr/bin/qemu-arm "$DESTINATION"/usr/bin
			;;
		*)
			echo "error: unsupported architecture: \"$ARCHITECTURE\""
			return 1;;
	esac
}

function gentooinstall_phase_resolvconf
{
	if [ ! -f "$DESTINATION/etc/resolv.conf" ]; then
		echo "Patching /etc/resolv.conf"
		echo "nameserver 8.8.8.8" >>"$DESTINATION/etc/resolv.conf"
		echo "nameserver 8.8.4.4" >>"$DESTINATION/etc/resolv.conf"
	fi
}

# \brief Download the latest stage3 tarball
function gentooinstall_phase_stage3
{
	echo "Downloading the stage 3 tarball..."
	mkdir -p "$DESTINATION"
	if [ "$STAGE3" = "latest" ]; then
		case "$ARCHITECTURE" in
			"i486")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/x86/autobuilds/latest-stage3-i486.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/x86/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/x86/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"i686")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/x86/autobuilds/latest-stage3-i686.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/x86/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/x86/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"amd64")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/amd64/autobuilds/latest-stage3-amd64.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/amd64/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/amd64/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"armv4tl")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/arm/autobuilds/latest-stage3-armv4tl.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"armv5tel")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/arm/autobuilds/latest-stage3-armv5tel.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"armv6j")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/arm/autobuilds/latest-stage3-armv6j.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"armv6j_hardfp")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/arm/autobuilds/latest-stage3-armv6j_hardfp.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"armv7a")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/arm/autobuilds/latest-stage3-armv7a.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			"armv7a_hardfp")
				LATEST=$(wget --quiet http://distfiles.gentoo.org/releases/arm/autobuilds/latest-stage3-armv7a_hardfp.txt -O-| tail -n 1 | cut -d " " -f 1)
				BASENAME=$(basename "$LATEST")
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST" -O "$DESTINATION/$BASENAME"
				wget -q --show-progress "http://distfiles.gentoo.org/releases/arm/autobuilds/$LATEST.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
				;;
			*) exit 1;;
		esac
	else
		BASENAME=$(basename "$STAGE3")
		wget -q --show-progress "$STAGE3" -O "$DESTINATION/$BASENAME.tar.gz"
		wget -q --show-progress "$STAGE3.DIGESTS.asc" -O "$DESTINATION/$BASENAME.DIGESTS.asc"
	fi
}

function gentooinstall_phase_stage3digest
{
	echo -n "Verifying the cryptographic signature of the stage3 hashes... "
	gpg --keyserver hkps.pool.sks-keyservers.net --recv-keys 0xBB572E0E2D182910 >/dev/null 2>/dev/null
	gpg --verify "$DESTINATION/stage3-"*".tar.bz2.DIGESTS.asc" >/dev/null 2>/dev/null
	if [ $? -ne 0 ]; then
		echo "Failed."
		echo "error: the cryptographic signature of \"$DESTINATION/stage3-"*".tar.bz2.DIGESTS.asc\" could not be verified!"
		exit 1
	fi
	echo "Success."
}

function gentooinstall_phase_stage3hash
{
	echo -n "Verifying the hash of the stage3 tarball... "
	grep $(sha512sum "$DESTINATION/stage3-"*".tar.bz2") "$DESTINATION/stage3-"*".tar.bz2.DIGESTS.asc" >/dev/null
	if [ $? -ne 0 ]; then
		echo "Failed."
		echo "error: the downloaded file \"$DESTINATION/stage3-"*".tar.bz2\" does not match the sha512sum hash in \"$DESTINATION/stage3-"*".tar.bz2.DIGESTS.asc\""
		exit 1
	fi
	echo "Success."
}

function gentooinstall_phase_syslogng
{
	if $CHROOT; then
		env-update
		source /etc/profile
		
		emerge --quiet app-admin/syslog-ng
		if [ $? -eq 0 ]; then
			rc-update add syslog-ng default
		fi

		emerge --quiet app-admin/ccze
		if [ $? -eq 0 ]; then
			# Update /etc/syslog-ng/syslog-ng.conf to use ccze for color output on TTY12
			echo "LS0tIC9ldGMvc3lzbG9nLW5nL3N5c2xvZy1uZy5jb25mCTIwMTYtMDQtMjkgMTE6NTg6MDkuNzkzNzA2MjE3IC0wNjAwCisrKyAvZXRjL3N5c2xvZy1uZy9zeXNsb2ctbmcuY29uZi5uZXcJMjAxNi0wNC0yOSAxMjowMDo0Ni4yMjY1Njg5OTAgLTA2MDAKQEAgLTI3LDcgKzI3LDcgQEAKIGRlc3RpbmF0aW9uIG1lc3NhZ2VzIHsgZmlsZSgiL3Zhci9sb2cvbWVzc2FnZXMiKTsgfTsKIAogIyBCeSBkZWZhdWx0IG1lc3NhZ2VzIGFyZSBsb2dnZWQgdG8gdHR5MTIuLi4KLWRlc3RpbmF0aW9uIGNvbnNvbGVfYWxsIHsgZmlsZSgiL2Rldi90dHkxMiIpOyB9OworZGVzdGluYXRpb24gY29uc29sZV9hbGwgeyBwcm9ncmFtKCJjY3plIC1yID4+IC9kZXYvdHR5MTIiKTsgfTsKICMgLi4uaWYgeW91IGludGVuZCB0byB1c2UgL2Rldi9jb25zb2xlIGZvciBwcm9ncmFtcyBsaWtlIHhjb25zb2xlCiAjIHlvdSBjYW4gY29tbWVudCBvdXQgdGhlIGRlc3RpbmF0aW9uIGxpbmUgYWJvdmUgdGhhdCByZWZlcmVuY2VzIC9kZXYvdHR5MTIKICMgYW5kIHVuY29tbWVudCB0aGUgbGluZSBiZWxvdy4K" \
				| base64 --decode | patch -p0
		fi
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase syslogng
	fi
}

function gentooinstall_phase_timezone
{
	if $CHROOT; then
		env-update
		source /etc/profile
		echo "$TIMEZONE" >/etc/timezone
		emerge --config sys-libs/timezone-data
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase timezone -t "$TIMEZONE"
	fi
}

function gentooinstall_phase_update
{
	if $CHROOT; then
		env-update
		source /etc/profile
		
		# list the news to help the user debug any unexpected failures
		eselect news list
		emerge -1u --backtrack=1024 --quiet sys-apps/portage
		emerge -uDN --with-bdeps=y --backtrack=1024 --quiet world
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase update
	fi
}

function gentooinstall_phase_vim
{
	if $CHROOT; then
		env-update
		source /etc/profile
		
		emerge --quiet app-editors/vim
		if [ $? -eq 0 ]; then
			eselect editor set vi
		fi
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase vim
	fi
}

function gentooinstall_phase_xorg
{
	if $CHROOT; then
		env-update
		source /etc/profile
		
		case "$ARCHITECTURE" in
			"amd64")
				eselect profile set "default/linux/amd64/13.0/desktop"
				;;
			"armv4tl")
				eselect profile set "default/linux/arm/13.0/armv4/desktop"
				;;
			"armv5tel")
				eselect profile set "default/linux/arm/13.0/armv5te/desktop"
				;;
			"armv6j")
				eselect profile set "default/linux/arm/13.0/armv6j/desktop"
				;;
			"armv6j_hardfp")
				eselect profile set "default/linux/arm/13.0/armv6j/desktop"
				;;
			"armv7a")
				eselect profile set "default/linux/arm/13.0/armv7a/desktop"
				;;
			"armv7a_hardfp")
				eselect profile set "default/linux/arm/13.0/armv7a/desktop"
				;;
			*) exit 1;;
		esac
		
		echo 'VIDEO_CARDS="fbdev"' >>/etc/portage/make.conf
		
		env-update
		source /etc/profile
		emerge -uDN --with-bdeps=y --quiet world
		
		emerge --quiet x11-base/xorg-x11
	else
		cp -f "$THIS" "$DESTINATION/tmp"
		$SETARCH chroot "$DESTINATION" /tmp/gentooinstall --chroot --phase xorg
	fi
}

#------------------------------------------------------------------------------
# hard coded variables

CODENAME=gentooinstall
DISPLAYNAME="Gentoo Install"
VERSION="0.0.0.0"
DEBUG=false
TMP="/tmp"

#------------------------------------------------------------------------------
# default configuration

EMAIL=""
NICE=0
VERBOSITY=0
ARCHITECTURE=amd64
SETARCH=""
CHROOT=false
DEVICE=/tmp/none
DEVICE_PARTITION_TYPE=gpt
DEVICE_PARTITION_ALIGNMENT=4194304
STAGE3="latest"
DESTINATION=/mnt/gentoo
PHASES="stage3,stage3digest,stage3hash,extract,deletestage3,resolvconf,makeconf,mountchroot,portage,timezone,locale,update,vim,syslogng,packages"
PORTAGE="latest"
TIMEZONE="UTC"

#------------------------------------------------------------------------------
# command line arguments
#

if [ $# -eq 0 ]; then
	gentooinstall_help
	exit 1
fi

THIS="$0"
while [ $# -ne 0 ]; do
	case "$1" in
		"-a"|"--architecture")
			ARCHITECTURE="$2"
			shift 2
			;;
		"-b"|"--block-device")
			DEVICE="$2"
			shift 2
			;;
		"--block-device-partition-type")
			DEVICE_PARTITION_TYPE="$2"
			shift 2
			;;
		"--block-device-partition-alignment")
			DEVICE_PARTITION_ALIGNMENT="$2"
			shift 2
			;;
		"--chroot")
			CHROOT=true
			shift
			;;
		"-d"|"--destination")
			DESTINATION="$2"
			shift 2
			;;
		"-h"|"--help")
			gentooinstall_help
			exit
			;;
		"-p"|"--phase")
			PHASES="$2"
			shift 2
			;;
		"--portage")
			PORTAGE="$2"
			shift 2
			;;
		"--stage3")
			STAGE3="$2"
			shift 2
			;;
		"-t"|"--timezone")
			TIMEZONE="$2"
			shift 2
			;;
		*)
			echo "error: unrecognized argument \"$1\""
			exit 1
			break;;
	esac
done

if [ "$ARCHITECTURE"="i686" ]; then
	SETARCH="linux32"
fi

#------------------------------------------------------------------------------
# begin execution
#

gentooinstall_main
